version: 2.1

jobs:
  build_deploy:
    description: Build and Deploy application
    machine: true
    steps:
      - checkout
      - run:
          name: "Update Packages"
          command: sudo apt-get update
      - run:
          name: "Installing zip Package"
          command: sudo apt-get install zip unzip
      - run:
          name: "Download AWS CLI"
          command: sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" 
      - run:
          name: "Unzip AWS CLI Package"
          command: sudo unzip awscliv2.zip
      - run:
          name: "Install AWS CLI"
          command: sudo ./aws/install
      - run:
          name: "Create Application Package"
          command: sudo zip ${DEPLOY_APP_KEY} index.js
      - run:
          name: "Upload to S3"
          command: sudo aws s3 cp ${DEPLOY_APP_KEY} s3://${S3_BUCKET_NAME}
workflows:
  version: 2
  build_deploy:
    jobs:
      - build_deploy:
          filters:
            branches:
              only:
                - master